#!/usr/bin/env python3
"""
Prepare one block-B run (scroll cap) as an isolated git worktree.

Creates runs/<prefix>_cap<N> at the pinned commit for one folder set (see
SETS: the 14 roll titles, the 6 titles without rolls, or the hold-out), without
the reference episode folders and databases, then fills it with:
  - scripts_v3/config.py: SCROLL_MAX_FRAMES_PER_SAVE = N (the only code change;
    none for N = 150, the reference value);
  - data/episodes/<folder>/analysis/: the reference Stage I outputs
    raw_scenes_cache.json and initial_scene_analysis.json only (frames/ and
    analysis_manifest.json are regenerated by Stage II);
  - data/raw/<corpus>/: copies of the set's clips;
  - db/: IMDb files only, no .db; .env copied from the main checkout;
  - run_info.json with commit, code change, parameters, stopwords and the
    reference Stage II frames of the set.

Stage II, III and IV are run by run_headless.py, which fills the submitted
frames into run_info.json after Stage II together with the comparison against
the reference. The reference Stage II was made with other code/environment
(00f0cbc5 for the main corpus, pre-5fec349 for the hold-out), so a difference
is recorded, never a reason to stop.

No model call is made here.

Usage:
    python prepare_pipe_run.py --cap 150                   # runs/PIPE_cap150 (14 roll titles)
    python prepare_pipe_run.py --cap 150 --set noscroll    # runs/PIPE_noscroll_cap150 (6 titles)
    python prepare_pipe_run.py --cap 150 --set holdout     # runs/STAGE2_holdout_cap150 (Stage II check)
    python prepare_pipe_run.py --cap 100 --set ypm         # runs/PIPE_noscroll_cap100 (YPM only)
"""

import argparse
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from prepare_naive_run import (
    MAIN_ROOT,
    PRICING_USD_PER_1M,
    RUN_COMMIT,
    copy_support_files,
    create_worktree,
    git,
    model_params,
    stopwords_info,
)

JULY_CAP = 150
CAP_LINE = "SCROLL_MAX_FRAMES_PER_SAVE: Final[int] = {}"
STAGE1_FILES = ["raw_scenes_cache.json", "initial_scene_analysis.json"]
OCR_LANGUAGE = "en"

REFERENCE_NOTE = {
    "reference_stage2": "Main-corpus reference frames come from the Stage II of 2025-12-04 (commit 00f0cbc5), "
                        "hold-out ones from the Stage II of 2026-07-18..23; July 2026 reran only Stage III on them.",
    "ocr_language": "Both reference Stage II runs used PaddleOCR lang='en' (en_PP-OCRv5_mobile_rec, downloaded "
                    "2025-12-04). Rerunning Stage II with lang='en' reproduces them exactly on static scenes "
                    "(El_desorden_End 50/50, Blue_Eye_Samurai_End 44/44, Wild_Strawberries_Opening 18/18); "
                    "lang='it' (latin model) does not (37/50, 30/44, 16/18). See revision_checks/.",
    "code_difference": "Between 00f0cbc5 and f9c9bb6 Stage II changes only in 5fec349 (scroll flow percentile "
                       "chosen by scroll direction); the utils functions used by Stage II are identical. Remaining "
                       "differences from the reference are expected only in rolls affected by 5fec349.",
    "decision": "Block B uses PIPE_cap150 (this code, lang='en') as its internal reference; comparison with the "
                "July numbers is reported with the 5fec349 difference.",
}

# Folder sets: clips folder under data/raw, reference Stage II frames count,
# product count used in the export name, and the run id prefix.
SETS = {
    # the 14 titles with credit rolls (block B proper)
    "scroll": {
        "corpus": "main_corpus_cut", "expected_reference": 963, "products": 14, "prefix": "PIPE",
        "reference": "Stage II of 2025-12-04, commit 00f0cbc5",
        "folders": [
            "Amelie", "Dark_1x9", "El_desorden_que_dejas_S01E03_End",
            "El_desorden_que_dejas_S01E03_Opening", "Eternal_Sunshine_of_the_Spotless_Mind",
            "Fight_Club", "Hill_Street_Blues_1x13", "La_grande_bellezza", "La_piovra_1x2",
            "Maigret_S03E01_End", "Maigret_S03E01_Opening", "Planet_Earth_S01E10",
            "Prime_Suspect_1x1", "Psycho", "Romanzo_criminale_S01E01_End",
            "Romanzo_criminale_S01E01_Opening", "Se7en",
        ],
    },
    # the 6 selection titles without rolls in the reference Stage II
    "noscroll": {
        "corpus": "main_corpus_cut", "expected_reference": 291, "products": 6, "prefix": "PIPE_noscroll",
        "reference": "Stage II of 2025-12-04, commit 00f0cbc5",
        "folders": [
            "8_e_mezzo", "Apocalypse_Now", "Chernobyl_S01E01_End", "Chernobyl_S01E01_Opening",
            "The_World_At_War_S01E03_End", "The_World_At_War_S01E03_Opening",
            "Twin_Peaks_1x3", "Yes,_Prime_Minister_1x8",
        ],
    },
    # the only no-roll-set folder where a roll appears today: redone at cap != 150,
    # the other 7 folders are taken from PIPE_noscroll_cap150 (the incremental
    # context never crosses folders, so reusing them is exact)
    "ypm": {
        "corpus": "main_corpus_cut", "expected_reference": 16, "products": 1, "prefix": "PIPE_noscroll",
        "reference": "Stage II of 2025-12-04, commit 00f0cbc5",
        "folders": ["Yes,_Prime_Minister_1x8"],
        "composition": {
            "redone_in_this_run": ["Yes,_Prime_Minister_1x8"],
            "taken_from_PIPE_noscroll_cap150": [
                "8_e_mezzo", "Apocalypse_Now", "Chernobyl_S01E01_End", "Chernobyl_S01E01_Opening",
                "The_World_At_War_S01E03_End", "The_World_At_War_S01E03_Opening", "Twin_Peaks_1x3",
            ],
            "why": "Yes,_Prime_Minister_1x8 scene_5 is a roll today (5fec349) and its interval is capped "
                   "(150 vs 159 uncapped); the other 7 folders have no roll, so the cap does not change them.",
        },
    },
    # the 5 hold-out titles: Stage II only, to identify the code used in July
    "holdout": {
        "corpus": "hold_out", "expected_reference": 207, "products": 5, "prefix": "STAGE2_holdout",
        "reference": "Stage II of 2026-07-18..23 (before 5fec349)",
        "folders": [
            "3_Percent_S01E06_End", "3_Percent_S01E06_Opening", "Blue_Eye_Samurai_S01E01_End",
            "Honeyland_End", "Persepolis_End", "Persepolis_Opening",
            "Wild_Strawberries_End", "Wild_Strawberries_Opening",
        ],
    },
}


def set_cap(run_dir: Path, cap: int) -> list[str]:
    if cap == JULY_CAP:
        return []
    config_py = run_dir / "scripts_v3" / "config.py"
    text = config_py.read_text(encoding="utf-8")
    old, new = CAP_LINE.format(JULY_CAP), CAP_LINE.format(cap)
    if text.count(old) != 1:
        sys.exit(f"Expected exactly one '{old}' in {config_py}")
    config_py.write_text(text.replace(old, new), encoding="utf-8")
    return [git("diff", "--", "scripts_v3/config.py", cwd=run_dir)]


def copy_stage1(run_dir: Path, folders: list[str]) -> None:
    for folder in folders:
        src = MAIN_ROOT / "data" / "episodes" / folder / "analysis"
        dst = run_dir / "data" / "episodes" / folder / "analysis"
        dst.mkdir(parents=True)
        for name in STAGE1_FILES:
            shutil.copy2(src / name, dst / name)


def reference_frames(folder_set: dict) -> dict[str, list[str]]:
    frames = {
        f: sorted(p.name for p in (MAIN_ROOT / "data" / "episodes" / f / "analysis" / "frames").glob("*.jpg"))
        for f in folder_set["folders"]
    }
    total = sum(map(len, frames.values()))
    if total != folder_set["expected_reference"]:
        sys.exit(f"Reference has {total} frames, expected {folder_set['expected_reference']}")
    return frames


def write_run_info(run_dir: Path, run_id: str, cap: int, set_name: str, code_diff: list[str]) -> None:
    folder_set = SETS[set_name]
    folders = folder_set["folders"]
    info = {
        "run_id": run_id,
        "block": "B - scroll cap" if set_name != "holdout" else "Stage II check on the hold-out (no Stage III)",
        "folder_set": set_name,
        **({"composition": folder_set["composition"]} if "composition" in folder_set else {}),
        "prepared_at": datetime.now(timezone.utc).isoformat(),
        "git_commit": git("rev-parse", "HEAD", cwd=run_dir),
        "code_modifications": code_diff,
        "parameters": {
            "SCROLL_MAX_FRAMES_PER_SAVE": cap,
            "stages": ["stage2", "stage3", "stage4"],
            "naive_mode": False,
            "stage1": "not rerun: reference raw_scenes_cache.json + initial_scene_analysis.json copied",
            "stage2_scenes": "all candidate scenes of initial_scene_analysis.json, in file order (as in the reference)",
            "ocr_engine": "paddleocr",
            # The reference Stage II (Dec 2025 main corpus, Jul 2026 hold-out) used lang="en"
            # (en_PP-OCRv5_mobile_rec); "it" loads latin_PP-OCRv5_mobile_rec and selects other frames.
            "ocr_language": OCR_LANGUAGE,
            **model_params(run_dir),
        },
        "source": {
            "stage1_from": f"data/episodes/<folder>/analysis at commit {RUN_COMMIT}",
            "reference_stage2": folder_set["reference"],
            "july_reference_db": "db/FUZZY88_GPT_SOL_STANDARD_25products_tvcredits_v3.db",
        },
        "stopwords": stopwords_info(run_dir),
        "pricing_usd_per_1M_tokens": PRICING_USD_PER_1M,
        "expected_export_csv": f"{run_id}_FUZZY88_GPT_SOL_STANDARD_{folder_set['products']}products.csv",
        # The reference Stage II predates 5fec349: compare, never stop.
        "stop_if_stage2_differs_from_reference": False,
        "reference_note": REFERENCE_NOTE,
        "reference_frames_total": folder_set["expected_reference"],
        "reference_frames": reference_frames(folder_set),
        # Filled by run_headless.py after Stage II.
        "submitted_frames_total": None,
        "submitted_frames": {f: None for f in folders},
    }
    (run_dir / "run_info.json").write_text(json.dumps(info, indent=2, ensure_ascii=False), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--cap", type=int, required=True)
    parser.add_argument("--set", dest="set_name", choices=sorted(SETS), default="scroll")
    args = parser.parse_args()
    cap, set_name = args.cap, args.set_name

    run_id = f"{SETS[set_name]['prefix']}_cap{cap}"
    run_dir = MAIN_ROOT / "runs" / run_id
    if run_dir.exists():
        sys.exit(f"{run_dir} already exists: a run is never overwritten")

    folders = SETS[set_name]["folders"]
    create_worktree(run_dir)
    code_diff = set_cap(run_dir, cap)
    copy_stage1(run_dir, folders)
    copy_support_files(run_dir, folders, SETS[set_name]["corpus"])
    write_run_info(run_dir, run_id, cap, set_name, code_diff)
    print(f"{run_id}: prepared, set={set_name}, cap={cap}, code changes: {len(code_diff)}")


if __name__ == "__main__":
    main()
